name: Release version
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Create release version and commit it
    runs-on: ubuntu-20.04
    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '14.20.0'
    - run: git config --global user.email "igortrinidad@users.noreply.github.co"
    - run: git config --global user.name "Igor Trindade"
    - run: pwd && npm ci
    - run: npm run release
    # - run: git push --follow-tags origin master

